executor: slurm
jobs: unlimited

set-resources:
  dragen_index:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 52
    cpus_per_task: 52
    mem: 500000MB
  unmapped_bam:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  collect_quality_yield_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 4
    cpus_per_task: 4
    mem: 32000MB
  unmapped_bam_to_aligned:
    runtime: 7200m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 5days
    threads: 52
    cpus_per_task: 52
    mem: 500000MB
  collect_unsorted_readgroup_bam_quality_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 4
    cpus_per_task: 4
    mem: 32000MB
  mark_duplicates:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  sort_bam:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 26
    cpus_per_task: 26
    # Memory (in GB) must be AT LEAST double the number of threadsMB
    mem: 250000MB
  cross_check_fingerprints:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  base_recalibration:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 6
    cpus_per_task: 6
    mem: 62500MB
  check_contamination:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  gather_bqsr_reports:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  apply_bqsr:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  gather_recalibrated_bams:
    runtime: 240m
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  collect_readgroup_bam_quality_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  collect_aggregation_metrics:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  calculate_readgroup_checksum:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  convert_to_cram:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  check_prevalidation:
    runtime: 30m
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 30mins
    threads: 6
    cpus_per_task: 6
    mem: 62500MB
  validate_sam_file:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  collect_wgs_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  collect_raw_wgs_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  calibrate_dragen_str_model:
    runtime: 240m
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  scatter_interval_list:
    runtime: 30m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 30mins
    threads: 6
    cpus_per_task: 6
    mem: 62500MB
  haplotype_caller:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours,5days
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  dragen_hardfilter_gvcf:
    runtime: 720m
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  merge_gvcfs:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  sort_bamout:
    # sort_bamout_jobs: 1
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  merge_bamout:
    runtime: 240m
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 26
    cpus_per_task: 26
    mem: 250000MB
  reblock:
    runtime: 720m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 12hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB
  validate_gvcf:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 6
    cpus_per_task: 6
    mem: 62500MB
  collect_variant_calling_metrics:
    runtime: 240m
    constraint: cascadelake
    slurm_extra: "--exclude=z[1024,1062,1068] --cpu-freq=High-High:Performance"
    slurm_partition: 4hours
    threads: 13
    cpus_per_task: 13
    mem: 125000MB

use-apptainer: True
apptainer-prefix: workflow/rules/envs
apptainer-args: -B /data

retries: 3
# keep-incomplete: True
printshellcmds: True
slurm-requeue: False # Prevent jobs from being requeued, otherwise held infinitely
slurm-efficiency-report: True
rerun-incomplete: True
keep-going: True
